### ISSUE TITLE
Texte Transparent dans les formules mathématiques

### ISSUE THREAD

**Issue by monstercube** [Julien-Devos/INGInious-dark-theme#1]
Bonjour,

Comme décrit dans le titre, j'ai un problème avec les formules mathématiques. Comme vous pouvez le voir dans l'image suivante, le texte que j'écris dans les encadrés est blanc. Or comme le fond est blanc, je ne vois pas grand chose ¯\_(ツ)_/¯.
![image](https://user-images.githubusercontent.com/64208366/107225193-cb72f480-6a18-11eb-9751-ed96280437fc.png)

Vous pouvez normalement tester le problème par vous même en suivant le lien suivant : 
https://inginious.info.ucl.ac.be/course/LEPL1105

Merci Ju <3<3

**Comment by Julien-Devos** [comment]
Fixé :D !

**Comment by Julien-Devos** [comment]
Fixé :D !
